/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IHeroiconsOutlineHome: typeof import('~icons/heroicons-outline/home')['default']
    IHeroiconsSolidUser: typeof import('~icons/heroicons-solid/user')['default']
    'IMaterialSymbolsLight:dashboardRounded': typeof import('~icons/material-symbols-light/dashboard-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IHeroiconsOutlineHome: typeof import('~icons/heroicons-outline/home')['default']
  const IHeroiconsSolidUser: typeof import('~icons/heroicons-solid/user')['default']
  const 'IMaterialSymbolsLight:dashboardRounded': typeof import('~icons/material-symbols-light/dashboard-rounded')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}