// utils/dummyUsers.ts
export const COMPANIES = [
  "Benton, John B Jr",
  "Chanay, Jeffrey A Esq Bollinger Mach Shp & Shipyard",
  "Chemel, James L Cpa",
  "Feltz Printing Service",
  "Printing Dimensions",
  "Chapman, Ross E Esq Chapman, Ross E Esq Chapman, Ross E Esq Chapman, Ross E Esq",
  "Morlong Associates",
  "Commercial Press",
  "Truhlar And Truhlar Attys Commercial Press",
  "King, Christopher A Esq",
  "Dorl, James J Esq Dorl, James J Esq",
  "Rangoni Of Florence",
  "Feiner Bros",
  "Buckley Miller & Wright Buckley Miller & Wright",
  "Rousseaux, Michael Esq",
  "Century Communications",
  "Bolton, Wilbur Esq Bolton, Wilbur Esq Bolton, Wilbur Esq Bolton, Wilbur Esq Bolton, Wilbur Esq Bolton, Wilbur Esq Bolton, Wilbur Esq Bolton, Wilbur Esq",
  "T M Byxbee Company Pc",
  "Farmers Insurance Group",
  "Post Box Services Plus Post Box Services Plus Post Box Services Plus Post Box Services Plus",
  "Sport En Art",
  "C 4 Network Inc",
];

export const IMAGES = [
  "https://i.pravatar.cc/150?img=1",
  "https://i.pravatar.cc/150?img=2",
  "https://i.pravatar.cc/150?img=3",
  "https://i.pravatar.cc/150?img=4",
  "https://i.pravatar.cc/150?img=5",
  "https://i.pravatar.cc/150?img=6",
  "https://i.pravatar.cc/150?img=7",
  "https://i.pravatar.cc/150?img=8",
];

export const MEMBER_STATUSES = [
  "Free",
  "Basic",
  "Premium",
  "VIP",
  "Suspended",
  "Inactive",
];

export const COUNTRIES = [
  "Algeria",
  "Egypt",
  "Panama",
  "Slovenia",
  "South Africa",
  "Egypt",
  "Paraguay",
  "Serbia",
  "Egypt",
  "Mexico",
  "Romania",
  "Singapore",
  "Serbia",
  "Chile",
  "Philippines",
  "Venezuela",
  "Malaysia",
  "Netherlands",
  "Israel",
  "Argentina",
  "Paraguay",
  "Ecuador",
  "Tunisia",
  "Belarus",
  "Iceland",
  "Italy",
  "Argentina",
  "Ireland",
  "Romania",
  "Israel",
  "Hungary",
  "Honduras",
  "Australia",
  "Ukraine",
  "Qatar",
  "Cameroon",
  "Italy",
  "Venezuela",
  "Paraguay",
  "Puerto Rico",
  "Bolivia",
  "Argentina",
  "France",
  "Vietnam",
  "Belgium",
  "Canada",
  "Mexico",
  "Ecuador",
  "Finland",
  "Finland",
];
